In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
dataset = pd.read_csv("diabetes_012_health_indicators_BRFSS2015.csv")

In [5]:
dataset

Diabetes_012  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0                0.0     1.0       1.0        1.0  40.0     1.0     0.0   
1                0.0     0.0       0.0        0.0  25.0     1.0     0.0   
2                0.0     1.0       1.0        1.0  28.0     0.0     0.0   
3                0.0     1.0       0.0        1.0  27.0     0.0     0.0   
4                0.0     1.0       1.0        1.0  24.0     0.0     0.0   
...              ...     ...       ...        ...   ...     ...     ...   
253675           0.0     1.0       1.0        1.0  45.0     0.0     0.0   
253676           2.0     1.0       1.0        1.0  18.0     0.0     0.0   
253677           0.0     0.0       0.0        1.0  28.0     0.0     0.0   
253678           0.0     1.0       0.0        1.0  23.0     0.0     0.0   
253679           2.0     1.0       1.0        1.0  25.0     0.0     0.0   

        HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                        0.0           0.0     0.0  ...            1.0   
1                        0.0           1.0     0.0  ...            0.0   
2                        0.0           0.0     1.0  ...            1.0   
3                        0.0           1.0     1.0  ...            1.0   
4                        0.0           1.0     1.0  ...            1.0   
...                      ...           ...     ...  ...            ...   
253675                   0.0           0.0     1.0  ...            1.0   
253676                   0.0           0.0     0.0  ...            1.0   
253677                   0.0           1.0     1.0  ...            1.0   
253678                   0.0           0.0     1.0  ...            1.0   
253679                   1.0           1.0     1.0  ...            1.0   

        NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  \
0               0.0      5.0      18.0      15.0       1.0  0.0   9.0   
1               1.0      3.0       0.0       0.0       0.0  0.0   7.0   
2               1.0      5.0      30.0      30.0       1.0  0.0   9.0   
3               0.0      2.0       0.0       0.0       0.0  0.0  11.0   
4               0.0      2.0       3.0       0.0       0.0  0.0  11.0   
...             ...      ...       ...       ...       ...  ...   ...   
253675          0.0      3.0       0.0       5.0       0.0  1.0   5.0   
253676          0.0      4.0       0.0       0.0       1.0  0.0  11.0   
253677          0.0      1.0       0.0       0.0       0.0  0.0   2.0   
253678          0.0      3.0       0.0       0.0       0.0  1.0   7.0   
253679          0.0      2.0       0.0       0.0       0.0  0.0   9.0   

        Education  Income  
0             4.0     3.0  
1             6.0     1.0  
2             4.0     8.0  
3             3.0     6.0  
4             5.0     4.0  
...           ...     ...  
253675        6.0     7.0  
253676        2.0     4.0  
253677        5.0     2.0  
253678        5.0     1.0  
253679        6.0     2.0  

[253680 rows x 22 columns]

In [6]:
dataset.isnull().sum()

Diabetes_012            0
HighBP                  0
HighChol                0
CholCheck               0
BMI                     0
Smoker                  0
Stroke                  0
HeartDiseaseorAttack    0
PhysActivity            0
Fruits                  0
Veggies                 0
HvyAlcoholConsump       0
AnyHealthcare           0
NoDocbcCost             0
GenHlth                 0
MentHlth                0
PhysHlth                0
DiffWalk                0
Sex                     0
Age                     0
Education               0
Income                  0
dtype: int64

In [7]:
y = dataset.iloc[:,0].values

In [8]:
x = dataset.iloc[:,1:].values

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25)

In [11]:
#from sklearn.preprocessing import Normalizer

In [12]:
#normalizer = Normalizer()
#normalized_train_X = normalizer.fit_transform(x_train)

In [13]:
#normalized_test_x=normalizer.transform(x_test)

In [14]:
#y_train = np.array(y_train).reshape((-1, 375))

In [15]:
#y_test = np.array(y_test).reshape((-1, 125))

In [16]:
#from sklearn.preprocessing import MinMaxScaler
#target_scaler = MinMaxScaler()
#target_scaler.fit(y_train)
#y_train = target_scaler.transform(y_train)
#y_test = target_scaler.transform(y_test)

In [17]:
from sklearn.linear_model import LinearRegression
regr = LinearRegression()
regr.fit(x_train, y_train)

LinearRegression()

In [18]:
regr.score(x_test, y_test)

0.16764213857562027

In [19]:
yy=regr.predict(x_test).round()

In [21]:
yy

array([118209.,  99956.,  95915., 113540., 110467.,  98505., 117508.,
       103931., 122294., 102871., 145692., 116120., 139023., 135423.,
       103839., 117614., 127145., 129515., 126883.,  94667., 109685.,
       135046., 110015., 122598., 124749., 126836., 130135., 127433.,
       134897., 119396., 109562., 144733., 113488., 122970., 135083.,
       118551., 109737., 104525., 145003., 101427., 121373., 122087.,
       100167., 100398.,  97494., 133043., 127056., 112309., 132122.,
       104108., 118266., 131560., 107394., 104170., 113564., 120311.,
       136759., 143543., 117657., 140184., 136889., 145997., 131805.,
       104421., 109174.,  99682., 111866., 115032., 132127., 136442.,
        97689., 109827., 135245., 116437., 120079., 108347., 105789.,
       145408., 141350., 141252., 135185., 115141., 103933., 110078.,
       141185.,  96334., 117009., 118714., 114069., 123326., 133885.,
       114733., 139000., 132448., 134601., 130835., 138671., 124568.,
       110206., 1050

In [22]:
y_test

array([124940,  91651,  85979, 119198, 106928,  86909, 123047, 104070,
       128032,  98195, 139441, 116435, 136013, 136393,  96749, 125612,
       132201, 132817, 133594,  85979, 115368, 136393, 109670, 126424,
       128032, 132817, 131808, 132817, 136642, 123047, 113028, 138353,
       119198, 131630, 136736, 123047, 106928,  98195, 139441,  92721,
       126424, 128032,  91544,  93256,  86909, 134879, 133679, 116091,
       135700, 100732, 121540, 135617, 102112, 100732, 119198, 125612,
       135713, 138895, 125612, 137177, 135713, 138895, 134879, 102112,
       109670,  91330, 115368, 117764, 135428, 136013,  93470, 109670,
       137020, 124940, 128032, 109670,  96749, 138414, 137893, 137059,
       136393, 120050, 100732, 106928, 137059,  85093, 125612, 124940,
       116091, 126141, 136393, 117764, 137177, 135617, 136393, 135195,
       137059, 129600, 111620, 104070, 129600, 130791, 132817, 135428,
       100732, 135713, 123047, 138414, 138329, 104070, 123047,  98195,
      

In [23]:
from sklearn.metrics import accuracy_score,confusion_matrix,mean_squared_error, r2_score
accuracy_score(y_test, yy)
confusion_matrix(y_test, yy)
mse = mean_squared_error(y_test, yy)
r2 = r2_score(y_test, yy)

In [24]:
accuracy_score(y_test, yy)

0.0

In [25]:
confusion_matrix(y_test, yy)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [26]:
mse = mean_squared_error(y_test, yy)

In [27]:
mse 

40376282.272

In [28]:
r2

0.8541840456537795